### ISSUE TITLE
Null values from model prediction

### ISSUE THREAD

**Issue by YuanningEric** [DataX-JieHao/PASNet#1]
I tried to run the code with the train and the validation data provided with this repository, but encountered an error. The error is detected in the  _bce_for_one_class_ function from the _Imbalance_CostFunc.py_. It seems that the model generates many null values in the prediction, so that the _binary_cross_entropy_ function failed. 

Any suggestions to fix this issue?
![Screen Shot 2022-02-11 at 9 00 26 AM](https://user-images.githubusercontent.com/45788503/153635909-b03c8cd0-a5b9-435a-8507-184bf762ac58.png)

![Screen Shot 2022-02-11 at 9 04 08 AM](https://user-images.githubusercontent.com/45788503/153635832-306e10ee-ae1a-4278-b773-48899f8e185f.png)

**Comment by saichandra1** [comment]
@YuanningEric  Just confirming the dataset is the same dataset provided here. In that case, may I know library versions?

**Comment by YuanningEric** [comment]
> @YuanningEric Just confirming the dataset is the same dataset provided here. In that case, may I know library versions?

Hi, thanks for the reply! I downloaded the dataset from the main page of this repository. 
![Screen Shot 2022-02-11 at 12 24 52 PM](https://user-images.githubusercontent.com/45788503/153665301-622fab86-253d-45ab-8fde-21c23c56e536.png)

Since I am running the code on an institutional computing cluster, some library versions included in your _requirement.txt_ have been deprecated and therefore can not be used on the cluster.  Therefore, I used the most similar library versions as I can. I found that the pytorch version has to be 1.6.0 to let the code run, otherwise there are some other fetal errors. I have attached the library versions I used . Any suggestions on how to resolve the issue?

![Screen Shot 2022-02-11 at 12 31 25 PM](https://user-images.githubusercontent.com/45788503/153665870-2b1598ce-e4b0-4420-963d-aaa442c2372f.png)

**Comment by YuanningEric** [comment]
> @YuanningEric Just confirming the dataset is the same dataset provided here. In that case, may I know library versions?

Thanks, I have solved the issue. The version of Pandas and numpy library should be exactly the same with the ones specified in requirement.txt. I used a newer version of the libaries.

**Comment by saichandra1** [comment]
Thanks, @YuanningEric. This info helps for the future.
